### ISSUE TITLE
What causes the "NotImplementedError" in my Python code when I try to start advertising?

### ISSUE THREAD

**Issue by Desertgeek** [adafruit/Adafruit_CircuitPython_BLE#160]
I am working with Adafruit_CircuitPython_BLE on a MacBook running Monterey 12.3. The code below is an example from the Adafruit library (ble_advertising_simpletest.py).

`from adafruit_ble import BLERadio

from adafruit_ble.advertising import Advertisement

ble = BLERadio()
advertisement = Advertisement()
advertisement.short_name = "HELLO"
advertisement.connectable = True

while True:
    print(advertisement)
    ble.start_advertising(advertisement, scan_response=b"")
    while not ble.connected:
        pass
    print("connected")
    while ble.connected:
        pass
`
When I get to the "ble.start_advertising" line I get the "NotImplementedError".
The MacBook should support BLE since it communicates with my iPhone, right?

**Comment by dhalbert** [comment]
The underlying implementation for adafruit-blinka-bleio  on a host computer uses [[bleak](url)](https://github.com/hbldh/bleak)https://github.com/hbldh/[bleak](https://github.com/hbldh/bleak), which does not support peripheral mode at all. Your MacBook could act as a peripheral, but not via bleak. And when it talks to your phone, it is acting as a BLE central, almost certainly.

You _can_ do scanning on the MacBook, so you could have the phone advertise, and find it via scanning.

**Comment by Desertgeek** [comment]
Thank you Dan for responding. It is very helpful. I'm actually trying to communicate between my laptop and an Ardunio WiFi Rev2, not my iPhone. The Arduino, fitted with the CNC V3 shield, controls 2 stepper motors forming AZ & EL axes on a (home made) tracking mount. A USB camera is fixed on the mount and is plugged in to my laptop. A Python program running on the laptop uses OpenCV routines to report the centroid of a target object in the image from the camera. I want to pass the X,Y coordinates of this centroid from the laptop to the Arduino an command the mount to move to keep the target centered in the image.
Your suggestion makes sense - switching the roles and having the Arduino scan for the laptop instead of the other way around. I will work on that.
Thanks.
PS: I get a "404" error when I click on your link above.

**Comment by dhalbert** [comment]
Yes, switching roles sounds good. I fixed the link, sorry.

**Comment by Desertgeek** [comment]
I'm still missing something. Following the suggestion given above, I wrote the following **code for the ArduinoWiFi** as a peripheral (modified from one of the examples):

`#include <ArduinoBLE.h>

BLEService uartService("19B10000-E8F2-537E-4F6C-D104768A1214"); // Bluetooth® Low Energy UART Service

// Bluetooth® Low Energy LED Switch Characteristic - custom 128-bit UUID, read and writable by central
BLECharacteristic xCharacteristic("19B10001-E8F2-537E-4F6C-D104768A1214", (0), BLERead | BLENotify,  2);
BLECharacteristic yCharacteristic("19B10002-E8F2-537E-4F6C-D104768A1214", (0), BLERead | BLENotify,  2);

void setup() {
  Serial.begin(115200);
  while (!Serial);

  // begin initialization
  if (!BLE.begin()) {
    Serial.println("starting Bluetooth® Low Energy module failed!");
    while (1);
  }

  // set advertised local name and service UUID:
  BLE.setLocalName("ArduinoWiFi");
  BLE.setAdvertisedService(uartService);

  // add the characteristic to the service
  uartService.addCharacteristic(xCharacteristic);
  uartService.addCharacteristic(yCharacteristic);

  // add service
  BLE.addService(uartService);

  // set the initial value for the characeristic:
  xCharacteristic.writeValue(0);
  yCharacteristic.writeValue(0);

  // start advertising
  BLE.advertise();

  Serial.println("BLE Peripheral");
}

void loop() {
  // listen for Bluetooth® Low Energy peripherals to connect:
  BLEDevice central = BLE.central();

  // if a central is connected to peripheral:
  if (central) {
    Serial.print("Connected to central: ");
    // print the central's MAC address:`

When I run this on the Arduino and fire up "**LightBlue**" on my macBook I indeed "see" the Arduino in the list of peripherals:

<img width="580" alt="image" src="https://user-images.githubusercontent.com/26048621/163842246-ff10b289-b6ec-4246-906b-470ed258de4d.png">

The python code below (also adapted from an example) is running on the **macBook**:

from __future__ import print_function
from adafruit_ble import BLERadio  # BluetoothLE
from adafruit_ble.advertising.standard import ProvideServicesAdvertisement
from adafruit_ble.services.nordic import UARTService

ArduinoUUID = "A615EABE-E0DC-2996-57CD-84C3E542499F"
sender = BLERadio()
service = UARTService

def main():
    """
    Main method of the program
    """
    uart_connection = None
    if sender.connected:
        for connection in sender.connections:
            if UARTService in connection:
                uart_connection = connection
                print("got connection")
            break

    # See if any existing connections are providing UARTService.
    while True:
        if not uart_connection:
            print("Scanning...")
            for adv in sender.start_scan(ProvideServicesAdvertisement,
                                         timeout=15):
                print(adv.address)
                if UARTService in adv.services:
                    print("found a UARTService advertisement")
                    uart_connection = sender.connect(adv)
                    break
            # Stop scanning whether or not we are connected.
            sender.stop_scan()


When I run this (with Arduino running) I get the "Scanning" message in the _while_ loop and also the UUID of the Arduino that is reported in the "print(adv.address)" in the _for_ loop continuously scrolling down the output window. But it never makes the uart_connection! It is as if it doesn't recognize the UARTService.

Interestingly, if I run LightBlue while these two programs are running, the serial monitor running in the Arduino IDE shows that the Arduino "sees" the laptop as a central and reports it.

<img width="759" alt="image" src="https://user-images.githubusercontent.com/26048621/163844679-5f933690-448e-406c-a6ca-db8dcb3a57d3.png">

This does not appear in the serial monitor output unless LightBlue is running.
PS: I'm having a difficult time formatting the text in this post to distinguish text from code. :(
